name: lapisco_challenge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.0.9
  http: ^1.3.0
  fl_chart: ^0.70.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  collection: ^1.18.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/background2.png
    - assets/images/solanimacao.json
    - assets/images/solnubladoanimacao.json
    - assets/images/solchovendo.json
